# Generated by Django 3.1.2 on 2020-10-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=60)),
                ('contact_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=20)),
                ('blood_type', models.CharField(blank=True, choices=[('A +ve', 'A+'), ('B +ve', 'B+'), ('O +ve', 'O+'), ('AB +ve', 'AB+'), ('A -ve', 'A-'), ('B -ve', 'B-'), ('O -ve', 'O-'), ('AB -ve', 'AB-')], max_length=10)),
                ('organ_bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.organbank')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField(auto_now_add=True)),
                ('organ_bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.organbank')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
