# Generated by Django 3.1.2 on 2020-10-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolllist',
            name='organ_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organbank'),
        ),
        migrations.AlterField(
            model_name='organlist',
            name='organ_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organbank'),
        ),
    ]
