# Generated by Django 3.1.2 on 2020-10-04 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='mobile_number')),
                ('blood_type', models.CharField(blank=True, choices=[('A +ve', 'A+'), ('B +ve', 'B+'), ('O +ve', 'O+'), ('AB +ve', 'AB+'), ('A -ve', 'A-'), ('B -ve', 'B-'), ('O -ve', 'O-'), ('AB -ve', 'AB-')], max_length=10, verbose_name='blood_type')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='address')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart', models.BooleanField(default=False)),
                ('kidney', models.BooleanField(default=False)),
                ('liver', models.BooleanField(default=False)),
                ('cornea', models.BooleanField(default=False)),
                ('lung', models.BooleanField(default=False)),
                ('pancreas', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
