# Generated by Django 3.1.2 on 2020-10-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
    ]
